[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
KernelFunctions = "ec8451be-7e33-11e9-00cf-bbf324bd1392"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
PDMats = "90014a1f-27ba-587c-ab20-58faa44d9150"

[compat]
Documenter = "0.27"
PDMats = "0.11"
