name: Format check

on:
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1
      - run: |
          julia  -e 'using Pkg; Pkg.add("JuliaFormatter")'
          julia  -e 'using JuliaFormatter; format("."; verbose=true)'
      - run: |
          git diff > diff.txt
          if [ -s diff.txt ]; then
            echo 'code is not formatted correctly'
            exit 1
          else
            echo 'code is formatted correctly!'
            exit 0
          fi
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: diff-${{ github.event.number }}
          path: diff.txt
